server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  cloud:
    openfeign:
      client:
        config:
          client-cbr:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: full

cbr:
  api:
    base-url: https://www.cbr-xml-daily.ru
    daily-endpoint: /daily_json.js

logging:
  level:
    org.example: debug